version: "3.3"

services:

  app:
    container_name: app
    image: node:latest
    working_dir: '/usr/app'
    command: ["sh", "init.sh"]
    volumes:
      - '.:/usr/app'
    ports:
      - 3000:3000
